---
title: "PS270 Final Project"
author: Hannah Paley 
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how effective canvassing is as a method to get people to vote...especially in the upcoming election. I definitely want to try and do something related to this years election. I would also be interested in seeing whether one issue is the reason individuals vote for a certain candidate. 

## Project Proposal

Does personally knowing someone who has had an abortion impact an individual's stance on abortion? Within this study I am planning to look at whether knowing or not knowing someone who has had an abortion impacts how an individual views abortion legislation. I hypothesize that personally knowing someone who has had an abortion will positively correlate to somewhat or strongly opposing anti-abortion or anti-contraception legislation. I believe that being personally connected to someone who has had an abortion makes it more likely that an individual will support legislation that increases abortion access. Having this personal connection to abortion may make it so people feel the issue is "closer" to them than those who do not have a personal connection to abortion. My data sample is based off of a web-survey measuring individual abortion attitudes between February 23, 2024 - February 25, 2024. My unit of analysis is an individual person. The explanatory variable of interest is whether or not a surveyed individual knows someone who has had an abortion. The variable is coded as yes, yes, I have, or yes I know someone if the individual knows someone who has had an abortion, or no if the individual does not someone who has had an abortion. My outcome variable is whether an individual strongly supports, somewhat supports, somewhat opposes, or strongly opposes a nationwide ban on abortion at 16 weeks of pregnancy. I may also look at this same set of answers regarding the question of banning emergency contraceptives. If I observe more "strongly opposes" and "somewhat opposes" than other responses regarding my outcome variable, this would support my hypothesis. Conversely, if I observe more "strongly supports" and "somewhat supports" than other responses regarding my outcome variable, this would go against my hypothesis. A positive correlation between strongly or somewhat opposing anti-abortion legislation and knowing someone who has had an abortion would indicate support for my hypothesis. 